### ISSUE TITLE
Error Handling ??

### ISSUE THREAD

**Issue by skalyanapu-mtuity** [NaturalIntelligence/Stubmatic#2]
Hi,

Can I perform error handling on the validation errors, aroused due to the wrong input of post data?

For example I created an endpoint in response.yaml which accepts XML and returns a set of XML file already saved in project path.Still, it was fine was and working as expected, but I wanted to perform validations also on XML post body provided and throw error respectively can I do such things stubmatic.

Regards.

**Comment by amitguptagwl** [comment]
They purpose of creating the stubs is to avoid programming as much as possible to make it more QA friendly and make it testable. For this case,

1. You are aware with all possible error cases. (You must be otherwise you'll not be able to test those scenarios).
2. You must be willing to write a separate functional test to test each error scenario. You can do it only when set of input is unique.

Since set of input is gonna be unique to write proper tests, you can well handle it by writing multiple mappings in stubmatic without exception handling.

Let me know if I'm clear on my point. Otherwise I'll add some examples.

**Comment by skalyanapu-mtuity** [comment]
Okay got it.

Thank you!
